    <script id="imgBoxTemplate" type="text/jarty">
    {literal}
        <div class="itemBox">
            <div class="imageBox">
                <img src="/{$filename}" width="{$width}" height="{$height}" alt="" />
            </div>
            <div class="textBox">
                <span>lat={$lat}</span><br/>
                <span>lng={$lng}</span><br/>
            </div>
        </div>
    {/literal}
    </script>
