<?php
require_once '../../vendor/autoload.php';
require_once '../../lib/Datatype.php';
/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-06-08 at 22:35:27.
 */
class DatatypeTest extends PHPUnit_Framework_TestCase
{

	private $object;

    /**
     * @covers _Integer::set
     * @covers _Integer::get
     * @covers _Integer::isValid
     */
    public function test_Integer()
    {
		$_ = $this;
		$tests = array(
			array(0, true),
			array(-1, true),
			array(99999, true),
			array(0.1, false),
			array('A', false),
			array('', false),
		);
		
		$_->object = new _Integer;
		$_->myLoop($tests);
		
    }

    /**
     * @covers _Float::set
     * @covers _Float::get
     * @covers _Float::isValid
     */
    public function test_Float()
    {
		$_ = $this;
		$tests = array(
			array(0, true),
			array(1, true),
			array(0.1, true),
			array(99999, true),
			array(99999.9999, true),
			array('A', false),
			array('', false),
		);
		
		$_->object = new _Float;
		$_->myLoop($tests);
    }



    /**
     * @covers _String::set
     * @covers _String::get
     * @covers _String::isValid
     */
    public function test_String()
    {
		$_ = $this;
		$tests = array(
			array('', true),
			array('ABCD', true),
			array('日本語', true),
			array(0.1, false),
			array(99999, false),
			array(99999.9999, false),
		);
		
		$_->object = new _String;
		$_->myLoop($tests);
		
    }
	
	
	public function myLoop($tests)
	{
		$_ = $this;
		foreach($tests as $test) {
			$testValue = array_shift($test);
			$resultValue = array_shift($test);
			//echo "testValue=$testValue\n";
			//echo "resultValue=$resultValue\n";

			$_->object->set($testValue);

			$this->assertEquals($testValue, $_->object->get());
			$this->assertEquals($resultValue, $_->object->isValid());
		}
	}

}
