<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-06-08 at 23:30:10.
 */
class DBAccessTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var DBAccess
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DBAccess;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers DBAccess::insertSet
     * @todo   Implement testInsertSet().
     */
    public function testInsertSet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DBAccess::updateSet
     * @todo   Implement testUpdateSet().
     */
    public function testUpdateSet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DBAccess::saveSet
     * @todo   Implement testSaveSet().
     */
    public function testSaveSet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DBAccess::delete
     * @todo   Implement testDelete().
     */
    public function testDelete()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DBAccess::resetAutoIncrement
     * @todo   Implement testResetAutoIncrement().
     */
    public function testResetAutoIncrement()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DBAccess::getRows
     * @todo   Implement testGetRows().
     */
    public function testGetRows()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DBAccess::getAllRows
     * @todo   Implement testGetAllRows().
     */
    public function testGetAllRows()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DBAccess::query
     * @todo   Implement testQuery().
     */
    public function testQuery()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DBAccess::close
     * @todo   Implement testClose().
     */
    public function testClose()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
