<!-- userauth/includes/loginForm.inc -->
<div class="table">
<form id="UserauthForm">
<table>
<tr>
	<th><label>username</label></th>
	<td><input type="text" id="Userauth-username" value="" /></td>
</tr>
<tr>
	<th><label>password</label></th>
	<td><input type="password" id="Userauth-password" value="" /></td>
</tr>
</table>
<div class="button">
<input type="button" id="UserauthLoginButton" value="Login" />
</div>
</form>
</div>
<!-- end of userauth/includes/loginForm.inc -->
