<!-- userauth/includes/loginForm.inc -->
<div class="container">
<form id="UserauthForm">
<div class="form-group">
	<label class="sr-only" for="Userauth-username">username</label>
	<input type="text" class="form-control input-lg" id="Userauth-username" name="Userauth-username" placeholder="username" value="" />
</div>

<div class="form-group">
	<label class="sr-only" for="Userauth-password">password</label>
	<input type="password" class="form-control input-lg" id="Userauth-password" name="Userauth-password" placeholder="password" value="" />
</div>

<div class="button">
	<button type="button" class="btn btn-primary btn-block" id="UserauthLoginButton">Login</button>
</div>
</form>
</div>
<!-- end of userauth/includes/loginForm.inc -->
