<!-- userauth/includes/logout.inc -->
<div class="container">
<div class="page-header">
    <div class="col-lg-12">
        <h1>ログアウトしました</h1>
    </div>
</div><!-- /page-header -->
</div><!-- /container -->
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <p>
                <span>ありがとうございました。またのご利用をお待ちしております。</span>
            </p>
        </div><!-- /col-lg-12 -->
    </div><!-- /row -->
</div><!-- /container -->
<!-- end of userauth/includes/logout.inc -->
